//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub use super::album::Entity as Album;
pub use super::artist::Entity as Artist;
pub use super::like::Entity as Like;
pub use super::playlist::Entity as Playlist;
pub use super::tag::Entity as Tag;
pub use super::track::Entity as Track;
pub use super::user::Entity as User;
